/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoRosanTransports.view;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import projetoRosanTransports.data.administradorData;
import projetoRosanTransports.data.motoristaData;
import projetoRosanTransports.model.administradorModel;
import projetoRosanTransports.model.motoristaModel;

/**
 *
 * @author Rafaella Alves Silva
 */
public class JFLogin extends javax.swing.JFrame {
    
    motoristaModel obj1 = new motoristaModel();
    administradorModel obj2 = new administradorModel();
    motoristaData DAO1 = new motoristaData();
    administradorData DA02 = new administradorData();
    JFPrincipal tela;
    /**
     * Creates new form JFLogin
     */
    
    public JFLogin() {
        initComponents();
        
       jlEsqSenha.setForeground(Color.DARK_GRAY);
       tela = new JFPrincipal();
       tela.setVisible(true);
       tela.setEnabled(false);
       
       jlAlerta1.setVisible(false);
       jlAlerta2.setVisible(false);
        
        this.getContentPane().setBackground(new Color(153,153,153));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/projetoRosanTransports/imagens/caminhao3.jpg")));
    }
    
    public void ValidaLogin(){
        try{
            obj1 = DAO1.validarUsuario(jtUsuario.getText(), jpfSenha.getText());
            if(obj1==null){
                obj2 = DA02.validarUsuario(jtUsuario.getText(), jpfSenha.getText());
                if(obj2==null){
                    JOptionPane.showMessageDialog(this, "Acesso Negado \nUsuário não encontrado no sistema!", "Login", JOptionPane.ERROR_MESSAGE);
                }else{
                    tela.start2(obj2);
                    tela.setEnabled(true);
                    dispose();
                }
            }else{
                tela.start1(obj1);
                tela.setEnabled(true);
                dispose();  
            }
        }catch(Exception e){
            if (jtUsuario.getText().equals("") && jpfSenha.getText().equals("")) {
                jlAlerta1.setVisible(true);
                jlAlerta1.setForeground(Color.RED);
                jlAlerta2.setVisible(true);
                jlAlerta2.setForeground(Color.RED);
                JOptionPane.showMessageDialog(this, "Acesso Negado \nCampo Usuário e Senha não Preenchidos", "Login", JOptionPane.ERROR_MESSAGE);
            } else {
                if (jtUsuario.getText().equals("")) {
                    jlAlerta1.setVisible(true);
                    jlAlerta1.setForeground(Color.RED);
                    JOptionPane.showMessageDialog(this, "Acesso Negado \nCampo Usuário não Preenchido", "Login", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (jpfSenha.getText().equals("")) {
                        jlAlerta2.setVisible(true);
                        jlAlerta2.setForeground(Color.RED);
                        JOptionPane.showMessageDialog(this, "Acesso Negado \nCampo Senha não Preenchido", "Login", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
            if (jtUsuario.getText().length() < 0 && jpfSenha.getText().length() < 0) {
                jlAlerta1.setVisible(false);
                jlAlerta2.setVisible(false);
                jpfSenha.setText("");
                JOptionPane.showMessageDialog(this, "Acesso Negado \n Login ou Senha Incorretos!", "Login", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jpfSenha = new javax.swing.JPasswordField();
        jbEntrar = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jlEsqSenha = new javax.swing.JLabel();
        jlAlerta2 = new javax.swing.JLabel();
        jlAlerta1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("R SILVA TRANSPORTES");
        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(153, 153, 153));
        setResizable(false);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Cinzel Black", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Login");
        jTextField1.setBorder(null);
        jTextField1.setSelectionColor(new java.awt.Color(0, 0, 153));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoRosanTransports/imagens/Logo - Copia.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Cinzel Black", 0, 14)); // NOI18N
        jLabel3.setText("Usuário:");

        jLabel4.setFont(new java.awt.Font("Cinzel Black", 0, 14)); // NOI18N
        jLabel4.setText("Senha:");

        jtUsuario.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jtUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtUsuarioKeyPressed(evt);
            }
        });

        jpfSenha.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        jpfSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jpfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpfSenhaKeyPressed(evt);
            }
        });

        jbEntrar.setBackground(new java.awt.Color(0, 0, 0));
        jbEntrar.setFont(new java.awt.Font("Cinzel Black", 0, 12)); // NOI18N
        jbEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jbEntrar.setText("Entrar");
        jbEntrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEntrarActionPerformed(evt);
            }
        });

        jbSair.setBackground(new java.awt.Color(0, 0, 0));
        jbSair.setFont(new java.awt.Font("Cinzel Black", 0, 12)); // NOI18N
        jbSair.setForeground(new java.awt.Color(255, 255, 255));
        jbSair.setText("Sair");
        jbSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jlEsqSenha.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        jlEsqSenha.setText("*Esqueceu Senha?");
        jlEsqSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlEsqSenhaMouseClicked(evt);
            }
        });

        jlAlerta2.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        jlAlerta2.setText("*Campo obrigatório");

        jlAlerta1.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        jlAlerta1.setText("*Campo obrigatório");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlAlerta2))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addGap(44, 44, 44)
                            .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jpfSenha, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlAlerta1)))
                    .addComponent(jlEsqSenha))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlAlerta1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jlAlerta2))
                        .addGap(4, 4, 4)
                        .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlEsqSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        // TODO add your handling code here:
        System.exit(0); 
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEntrarActionPerformed
        // TODO add your handling code here:
        ValidaLogin();
    }//GEN-LAST:event_jbEntrarActionPerformed

    private void jpfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfSenhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ValidaLogin();
        }
    }//GEN-LAST:event_jpfSenhaKeyPressed

    private void jtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtUsuarioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ValidaLogin();
        }
    }//GEN-LAST:event_jtUsuarioKeyPressed

    private void jlEsqSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlEsqSenhaMouseClicked
        // TODO add your handling code here:
        JFEsqSenha tela = new JFEsqSenha();
        tela.setVisible(true);
    }//GEN-LAST:event_jlEsqSenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton jbEntrar;
    private javax.swing.JButton jbSair;
    private javax.swing.JLabel jlAlerta1;
    private javax.swing.JLabel jlAlerta2;
    private javax.swing.JLabel jlEsqSenha;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
